services:
  postgres:
    image: postgres:16
    container_name: tmdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d data" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin123
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  
  backend:
    build: 
     context: .
     dockerfile: backend/Dockerfile
    container_name : mvs_tracker_api
    ports:
      - "8000:8000"
    env_file:
    - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
    working_dir: /app


    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mvs_tracker_frontend
    ports: 
      - "5500:80"
    depends_on:
      - backend
volumes:
  postgres_data:
  pgadmin_data: